/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from "three";
import { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    [key: string]: THREE.Mesh;
  };
  materials: {
    [key: string]: THREE.MeshStandardMaterial;
  };
};
export default function OfficeModel(props) {
  const group = useRef();
  const { nodes, materials, scene } = useGLTF(
    "/officeScene.gltf"
  ) as GLTFResult;
  
return (
    <group ref={group} {...props} dispose={null}>
      <group position={[2.47, 1.04, -7.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019.geometry}
          material={materials.cupboard1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019_1.geometry}
          material={materials.cupboard2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019_2.geometry}
          material={materials.cupboardhandle}
        />
      </group>
      <group
        position={[5.09, 0.49, -7.49]}
        rotation={[-Math.PI, 1.54, -Math.PI]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013.geometry}
          material={materials.pcblack}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_1.geometry}
          material={materials.pcgrey}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_2.geometry}
          material={materials.pcblack2}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mouse.geometry}
        material={nodes.mouse.material}
        position={[7.87, 1.52, -6.79]}
        rotation={[0, 1.36, 0]}
      />
      <group
        position={[6.21, 0.02, -4.43]}
        rotation={[0, 1.31, 0]}
        scale={1.09}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.memur_kultuğu001.geometry}
          material={materials.keyboard1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.memur_kultuğu001_1.geometry}
          material={materials.chairarms}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.desk.geometry}
        material={materials.desk}
        position={[9.45, 0.51, -5.49]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
      />
      <group position={[8.42, 1.6, -7.35]} rotation={[0, 0.87, 0]} scale={1.14}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006.geometry}
          material={materials.screen}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006_1.geometry}
          material={materials.monitorblk}
        />
      </group>
      <group
        position={[6.86, 1.59, -7.75]}
        rotation={[0, 1.54, 0]}
        scale={1.14}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_1.geometry}
          material={materials.monitorblk}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_2.geometry}
          material={materials.screen}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mousepad.geometry}
        material={materials.Material}
        position={[7.88, 1.51, -6.81]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.34, 0, 0.34]}
      />
      <group
        position={[1.77, 2.32, -7.76]}
        rotation={[0, 0, 0.03]}
        scale={[1.37, 1.29, 1]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.book_set_Plane036.geometry}
          material={materials.book_set2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.book_set_Plane036_1.geometry}
          material={materials.book_set4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.book_set_Plane036_2.geometry}
          material={materials.book_set5}
        />
      </group>
      <group position={[6.05, -0.08, -4.83]} scale={[2.63, 0.05, 2.63]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005.geometry}
          material={materials.rugin1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_1.geometry}
          material={materials.rugin2}
        />
      </group>
      <group
        position={[6.12, 1.58, -7.01]}
        rotation={[0.04, 1.57, 0]}
        scale={[0.02, 0.01, 0.02]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_1.geometry}
          material={materials.keyboard1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_2.geometry}
          material={materials.keyboard2}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pot.geometry}
        material={materials.glass}
        position={[3.04, 1.57, -7.77]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[2.57, 2.57, 1.4]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stem.geometry}
        material={materials.leafmaterial}
        position={[3.04, 1.57, -7.77]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[2.57, 2.57, 1.4]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.book2.geometry}
        material={materials.book2}
        position={[3.04, 1.57, -7.77]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[2.57, 2.57, 1.4]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.book1.geometry}
        material={materials.book1}
        position={[3.04, 1.57, -7.77]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[2.57, 2.57, 1.4]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.book3.geometry}
        material={materials.book3}
        position={[3.04, 1.57, -7.77]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[2.57, 2.57, 1.4]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plantleaf.geometry}
        material={materials.leafmaterial}
        position={[3.04, 1.57, -7.77]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[2.57, 2.57, 1.4]}
      />
      <group
        position={[10.45, 2.8, -1.28]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[2, 1.5, 0.03]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={materials.whiteboardtray}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_1.geometry}
          material={materials.whiteboard}
        />
      </group>
      <group
        position={[10.37, 1.43, -0.06]}
        rotation={[-Math.PI / 2, 1.57, 0]}
        scale={0.03}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006.geometry}
          material={materials.marker1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006_1.geometry}
          material={materials.markerwhite}
        />
      </group>
      <group
        position={[10.37, 1.52, 0.68]}
        rotation={[Math.PI / 2, 1.57, 0]}
        scale={0.03}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder007.geometry}
          material={materials.markerwhite}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder007_1.geometry}
          material={materials.marker2}
        />
      </group>
      <group
        position={[10.37, 1.52, -0.48]}
        rotation={[Math.PI / 2, 1.57, 0]}
        scale={0.03}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008.geometry}
          material={materials.markergreen}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008_1.geometry}
          material={materials.markerwhite}
        />
      </group>
      <group position={[-14.9, 10.11, -0.96]} scale={-3.53}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          material={materials.warm1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_1.geometry}
          material={materials.warm2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_2.geometry}
          material={materials.warm3}
        />
      </group>
      <group
        position={[-16.91, 9.58, -1.06]}
        rotation={[-Math.PI / 2, 0, -1.57]}
        scale={[3.05, 2.93, 3.05]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007.geometry}
          material={materials.warm4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_1.geometry}
          material={materials.warm2}
        />
      </group>
      <group
        position={[-14.17, 5.65, -4.43]}
        rotation={[-Math.PI / 2, 0, -3.1]}
        scale={[0.19, 0.16, 0.19]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_Circle002_1.geometry}
          material={materials.stringbase}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_Circle002_2.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_Circle002_3.geometry}
          material={materials["None.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_Circle002_4.geometry}
          material={materials.BRIDGEPIN}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_Circle002_5.geometry}
          material={materials.frets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_Circle002_6.geometry}
          material={materials.pcgrey}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_Circle002_7.geometry}
          material={materials.fretboard}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_Circle002_8.geometry}
          material={materials.guitar_white}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_Circle002_9.geometry}
          material={materials.guitar_body_SIDE}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_Circle002_10.geometry}
          material={materials.board}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_Circle002_11.geometry}
          material={materials.BRIDGE}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_Circle002_12.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_Circle002_13.geometry}
          material={materials["guitar_body.001"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials.guitarholder}
        position={[-14.18, 5.5, -4.68]}
        rotation={[-Math.PI, 0, 0]}
        scale={[0.06, 0.13, 0.06]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002.geometry}
          material={materials.guitarholder}
          position={[0.04, 0.11, -1.51]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.25, 0.5, 0.12]}
        />
      </mesh>
      <group
        position={[-15.28, 6.51, -4.42]}
        rotation={[-3.12, 0, 3.13]}
        scale={[0.22, 0.21, 0.33]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve2231_CUCurve2160_1.geometry}
          material={materials.bodymetal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve2231_CUCurve2160_2.geometry}
          material={materials.body}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve2231_CUCurve2160_3.geometry}
          material={materials.dials}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve2231_CUCurve2160_4.geometry}
          material={materials.pegs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve2231_CUCurve2160_5.geometry}
          material={materials.strings}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve2231_CUCurve2160_6.geometry}
          material={materials.headmetal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve2231_CUCurve2160_7.geometry}
          material={materials["backboards?"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve2231_CUCurve2160_8.geometry}
          material={materials.frets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve2231_CUCurve2160_9.geometry}
          material={materials.stringbase}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve2231_CUCurve2160_10.geometry}
          material={materials.bridge}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve2231_CUCurve2160_11.geometry}
          material={materials.guitarcutout}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve2231_CUCurve2160_12.geometry}
          material={materials.fretboard}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials.guitarholder}
        position={[-15.28, 6.3, -4.61]}
        rotation={[-Math.PI, 0, 0]}
        scale={[0.06, 0.13, 0.06]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials.guitarholder}
          position={[0.04, 0.11, -1.51]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.25, 0.5, 0.12]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DoorCutOut.geometry}
        material={nodes.DoorCutOut.material}
        position={[-7.43, 7.05, 13.83]}
        scale={[1.61, 3.04, 0.63]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall.geometry}
        material={nodes.wall.material}
        position={[-8.34, 8.03, 13.96]}
        rotation={[-Math.PI / 2, 1.57, 0]}
        scale={32.11}
      />
      <group
        position={[-7.5, 7.09, 14.17]}
        rotation={[-Math.PI / 2, 1.57, 0]}
        scale={[3.31, 2.87, 1.81]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002.geometry}
          material={materials.doorhandle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_1.geometry}
          material={materials.doorwindow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_2.geometry}
          material={materials.doorframe}
        />
      </group>
      <group position={[-7.69, 10.05, 23.31]} scale={[-10.38, 1, -8.98]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003.geometry}
          material={materials.warm5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_1.geometry}
          material={materials.porchwoodseams}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_2.geometry}
          material={materials.porchwood}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.porchrailing.geometry}
        material={materials.porchwood}
        position={[-18.01, 10.05, 23.31]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[-8.98, 1.03, 3.47]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.porchrailing001.geometry}
        material={materials.porchwood}
        position={[2.36, 10.05, 23.31]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[-8.98, 1.03, 3.47]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.paper_coffee_cup_low_export_Cylinder003.geometry}
        material={materials.hot_coffee_cup}
        position={[8.69, 1.51, -5.69]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
    </group>
  );
} 

useGLTF.preload("/workingOffice.gltf");
